### ISSUE TITLE
Consider adding a changelog

### ISSUE THREAD

**Issue by freekmurze** [DragonBe/hibp#5]
A changelog is a file in project where are the changes are listed, so users have one place to look up all changes. More info: https://keepachangelog.com/en/1.0.0/  Example: https://github.com/spatie/laravel-medialibrary/blob/master/CHANGELOG.md

You could opt to add one to your project. If you do add it, great! If you don't, that's fine too, package creator is the boss 😄

**Comment by DragonBe** [comment]
I'm relying on the tags for now, but it makes sense to add them into a changelog file with the project so everyone has a full list of changes with the project.
Let's add it!
